import type { ComponentTemplate } from '../../types';

export const chartLine1Template: Omit<ComponentTemplate, 'renderer'> = {
  id: 'chart-line-1',
  category: 'chart',
  group: '折线图',
  label: '折线图·样式1',
  previews: { dark: 'previews/chart-line-1.dark.svg', light: 'previews/chart-line-1.light.svg' },
  defaultSize: { w: 700, h: 300 },
  dataProtocol: 'axis',
  hasDataTab: true,
  hasEventTab: true,
  styleSchema: [
    { key: 'boardEnabled', label: '底板框', type: 'switch', group: '底板框' },
    { key: 'boardTitle', label: '标题文字', type: 'text', group: '底板框' },
    { key: 'boardPadding', label: '内边距', type: 'number', min: 0, max: 40, step: 2, unit: 'px', group: '底板框' },
    { key: 'seriesColors', label: '系列颜色', type: 'colorList', group: '系列' },
    { key: 'lineSmooth', label: '平滑曲线', type: 'switch', group: '系列' },
    { key: 'lineWidth', label: '线宽', type: 'number', min: 1, max: 6, step: 0.5, unit: 'px', group: '系列' },
    { key: 'areaOpacity', label: '面积透明度', type: 'number', min: 0, max: 100, step: 5, unit: '%', group: '系列' },
    { key: 'showSymbol', label: '数据点标记', type: 'switch', group: '系列' },
    { key: 'showLabel', label: '数值标签', type: 'switch', group: '系列' },
    { key: 'showLegend', label: '显示图例', type: 'switch', group: '图例' },
    {
      key: 'legendPosition',
      label: '图例位置',
      type: 'select',
      options: [
        { label: '顶部居中', value: 'top' },
        { label: '右上', value: 'topRight' },
        { label: '底部居中', value: 'bottom' },
      ],
      group: '图例',
    },
    { key: 'showXAxis', label: '显示 X 轴', type: 'switch', group: '坐标轴' },
    { key: 'showYAxis', label: '显示 Y 轴', type: 'switch', group: '坐标轴' },
    { key: 'axisLabelColor', label: '轴标签颜色', type: 'color', group: '坐标轴' },
    { key: 'gridColor', label: '网格线颜色', type: 'color', group: '坐标轴' },
  ],
  defaultStyle: {
    dark: {
      boardEnabled: true,
      boardTitle: '折线图',
      boardPadding: 12,
      seriesColors: ['#2F7FF7', '#35E0FF', '#22C55E', '#F59E0B', '#EF4444', '#A78BFA', '#F472B6', '#34D399'],
      lineSmooth: true,
      lineWidth: 2,
      areaOpacity: 20,
      showSymbol: true,
      showLabel: false,
      showLegend: true,
      legendPosition: 'top',
      showXAxis: true,
      showYAxis: true,
      axisLabelColor: '#9FB3D1',
      gridColor: 'rgba(30,58,102,.6)',
    },
    light: {
      boardEnabled: true,
      boardTitle: '折线图',
      boardPadding: 12,
      seriesColors: ['#2F7FF7', '#0EA5E9', '#16A34A', '#D97706', '#DC2626', '#7C3AED', '#DB2777', '#059669'],
      lineSmooth: true,
      lineWidth: 2,
      areaOpacity: 15,
      showSymbol: true,
      showLabel: false,
      showLegend: true,
      legendPosition: 'top',
      showXAxis: true,
      showYAxis: true,
      axisLabelColor: '#6B7280',
      gridColor: 'rgba(228,231,237,.9)',
    },
  },
  defaultData: {
    categories: ['1月', '2月', '3月', '4月', '5月', '6月'],
    series: [
      { name: '供水量', data: [820, 932, 901, 1290, 1330, 1520] },
      { name: '售水量', data: [700, 810, 780, 1100, 1180, 1360] },
    ],
  },
};
